project:
  type: website

website:
  title: "Data visualization and transformation"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    toc: true

execute:
  freeze: auto