project:
  type: website

website:
  title: "Data visualization and transformation"
  navbar:
    tools:
        - icon: github
          href: https://github.com/data-science-with-r
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    toc: true
    highlight-style: a11y-dark

execute:
  freeze: auto